// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logistic.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// 快递100实时查询接口
// Post
type LogisticQueryRequest struct {
	// @inject_tag: form:"shop_id"
	ShopId string `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty" form:"shop_id"`
	// @inject_tag: form:"company"
	Company string `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty" form:"company"`
	// @inject_tag: form:"number"
	Number string `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty" form:"number"`
	// @inject_tag: form:"phone"
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty" form:"phone"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogisticQueryRequest) Reset()         { *m = LogisticQueryRequest{} }
func (m *LogisticQueryRequest) String() string { return proto.CompactTextString(m) }
func (*LogisticQueryRequest) ProtoMessage()    {}
func (*LogisticQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59d0a4b62ec9656f, []int{0}
}

func (m *LogisticQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogisticQueryRequest.Unmarshal(m, b)
}
func (m *LogisticQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogisticQueryRequest.Marshal(b, m, deterministic)
}
func (m *LogisticQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogisticQueryRequest.Merge(m, src)
}
func (m *LogisticQueryRequest) XXX_Size() int {
	return xxx_messageInfo_LogisticQueryRequest.Size(m)
}
func (m *LogisticQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogisticQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogisticQueryRequest proto.InternalMessageInfo

func (m *LogisticQueryRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *LogisticQueryRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *LogisticQueryRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *LogisticQueryRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type LogisticQueryData struct {
	Context              string   `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	FTime                string   `protobuf:"bytes,3,opt,name=fTime,proto3" json:"fTime,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AreaCode             string   `protobuf:"bytes,5,opt,name=areaCode,proto3" json:"areaCode,omitempty"`
	AreaName             string   `protobuf:"bytes,6,opt,name=areaName,proto3" json:"areaName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogisticQueryData) Reset()         { *m = LogisticQueryData{} }
func (m *LogisticQueryData) String() string { return proto.CompactTextString(m) }
func (*LogisticQueryData) ProtoMessage()    {}
func (*LogisticQueryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_59d0a4b62ec9656f, []int{1}
}

func (m *LogisticQueryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogisticQueryData.Unmarshal(m, b)
}
func (m *LogisticQueryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogisticQueryData.Marshal(b, m, deterministic)
}
func (m *LogisticQueryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogisticQueryData.Merge(m, src)
}
func (m *LogisticQueryData) XXX_Size() int {
	return xxx_messageInfo_LogisticQueryData.Size(m)
}
func (m *LogisticQueryData) XXX_DiscardUnknown() {
	xxx_messageInfo_LogisticQueryData.DiscardUnknown(m)
}

var xxx_messageInfo_LogisticQueryData proto.InternalMessageInfo

func (m *LogisticQueryData) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *LogisticQueryData) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *LogisticQueryData) GetFTime() string {
	if m != nil {
		return m.FTime
	}
	return ""
}

func (m *LogisticQueryData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LogisticQueryData) GetAreaCode() string {
	if m != nil {
		return m.AreaCode
	}
	return ""
}

func (m *LogisticQueryData) GetAreaName() string {
	if m != nil {
		return m.AreaName
	}
	return ""
}

type LogisticQueryResponse struct {
	State                string               `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	IsCheck              string               `protobuf:"bytes,2,opt,name=isCheck,proto3" json:"isCheck,omitempty"`
	Company              string               `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Number               string               `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	Data                 []*LogisticQueryData `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogisticQueryResponse) Reset()         { *m = LogisticQueryResponse{} }
func (m *LogisticQueryResponse) String() string { return proto.CompactTextString(m) }
func (*LogisticQueryResponse) ProtoMessage()    {}
func (*LogisticQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59d0a4b62ec9656f, []int{2}
}

func (m *LogisticQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogisticQueryResponse.Unmarshal(m, b)
}
func (m *LogisticQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogisticQueryResponse.Marshal(b, m, deterministic)
}
func (m *LogisticQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogisticQueryResponse.Merge(m, src)
}
func (m *LogisticQueryResponse) XXX_Size() int {
	return xxx_messageInfo_LogisticQueryResponse.Size(m)
}
func (m *LogisticQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogisticQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogisticQueryResponse proto.InternalMessageInfo

func (m *LogisticQueryResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *LogisticQueryResponse) GetIsCheck() string {
	if m != nil {
		return m.IsCheck
	}
	return ""
}

func (m *LogisticQueryResponse) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *LogisticQueryResponse) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *LogisticQueryResponse) GetData() []*LogisticQueryData {
	if m != nil {
		return m.Data
	}
	return nil
}

type LogisticPermissionRequest struct {
	// @inject_tag: form:"shop_id"
	ShopId               string   `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty" form:"shop_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogisticPermissionRequest) Reset()         { *m = LogisticPermissionRequest{} }
func (m *LogisticPermissionRequest) String() string { return proto.CompactTextString(m) }
func (*LogisticPermissionRequest) ProtoMessage()    {}
func (*LogisticPermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59d0a4b62ec9656f, []int{3}
}

func (m *LogisticPermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogisticPermissionRequest.Unmarshal(m, b)
}
func (m *LogisticPermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogisticPermissionRequest.Marshal(b, m, deterministic)
}
func (m *LogisticPermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogisticPermissionRequest.Merge(m, src)
}
func (m *LogisticPermissionRequest) XXX_Size() int {
	return xxx_messageInfo_LogisticPermissionRequest.Size(m)
}
func (m *LogisticPermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogisticPermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogisticPermissionRequest proto.InternalMessageInfo

func (m *LogisticPermissionRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

type LogisticPermissionResponse struct {
	IsAllow              bool     `protobuf:"varint,1,opt,name=is_allow,json=isAllow,proto3" json:"is_allow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogisticPermissionResponse) Reset()         { *m = LogisticPermissionResponse{} }
func (m *LogisticPermissionResponse) String() string { return proto.CompactTextString(m) }
func (*LogisticPermissionResponse) ProtoMessage()    {}
func (*LogisticPermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59d0a4b62ec9656f, []int{4}
}

func (m *LogisticPermissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogisticPermissionResponse.Unmarshal(m, b)
}
func (m *LogisticPermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogisticPermissionResponse.Marshal(b, m, deterministic)
}
func (m *LogisticPermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogisticPermissionResponse.Merge(m, src)
}
func (m *LogisticPermissionResponse) XXX_Size() int {
	return xxx_messageInfo_LogisticPermissionResponse.Size(m)
}
func (m *LogisticPermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogisticPermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogisticPermissionResponse proto.InternalMessageInfo

func (m *LogisticPermissionResponse) GetIsAllow() bool {
	if m != nil {
		return m.IsAllow
	}
	return false
}

func init() {
	proto.RegisterType((*LogisticQueryRequest)(nil), "LogisticQueryRequest")
	proto.RegisterType((*LogisticQueryData)(nil), "LogisticQueryData")
	proto.RegisterType((*LogisticQueryResponse)(nil), "LogisticQueryResponse")
	proto.RegisterType((*LogisticPermissionRequest)(nil), "LogisticPermissionRequest")
	proto.RegisterType((*LogisticPermissionResponse)(nil), "LogisticPermissionResponse")
}

func init() { proto.RegisterFile("logistic.proto", fileDescriptor_59d0a4b62ec9656f) }

var fileDescriptor_59d0a4b62ec9656f = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0xc9, 0xbf, 0x49, 0xda, 0xff, 0x08, 0x82, 0x4b, 0xd5, 0x6d, 0x4f, 0x25, 0x07, 0xe9,
	0xa9, 0x07, 0x15, 0x3c, 0x6b, 0xbd, 0x08, 0x22, 0x1a, 0x3c, 0x79, 0x29, 0xdb, 0x64, 0x34, 0x8b,
	0xc9, 0x6e, 0xcc, 0x6e, 0xa8, 0xfd, 0x38, 0x9e, 0xfc, 0x9a, 0xb2, 0x2f, 0x51, 0xeb, 0x0b, 0x9e,
	0x92, 0xdf, 0x3c, 0xcc, 0x3c, 0x33, 0x4f, 0x02, 0xdb, 0xa5, 0x7c, 0xe0, 0x4a, 0xf3, 0x6c, 0x56,
	0x37, 0x52, 0xcb, 0x64, 0x05, 0xc3, 0x4b, 0x5f, 0xb9, 0x69, 0xb1, 0x59, 0xa7, 0xf8, 0xd4, 0xa2,
	0xd2, 0x64, 0x1f, 0xfa, 0xaa, 0x90, 0xf5, 0x82, 0xe7, 0x34, 0x98, 0x04, 0xd3, 0xff, 0x69, 0x6c,
	0xf0, 0x22, 0x27, 0x14, 0xfa, 0x99, 0xac, 0x6a, 0x26, 0xd6, 0xf4, 0x9f, 0x15, 0x3a, 0x24, 0x7b,
	0x10, 0x8b, 0xb6, 0x5a, 0x62, 0x43, 0x7b, 0xae, 0xc3, 0x11, 0x19, 0x42, 0x54, 0x17, 0x52, 0x20,
	0x0d, 0x6d, 0xd9, 0x41, 0xf2, 0x1a, 0xc0, 0xce, 0x86, 0xf3, 0x39, 0xd3, 0xcc, 0x4d, 0x17, 0x1a,
	0x9f, 0xb5, 0xb7, 0xed, 0x90, 0x10, 0x08, 0x35, 0xaf, 0xd0, 0x9b, 0xda, 0x77, 0x33, 0xf9, 0xfe,
	0xd6, 0x14, 0x9d, 0xa1, 0x03, 0xb3, 0x87, 0xd2, 0x4c, 0xb7, 0xca, 0x1b, 0x7a, 0x22, 0x63, 0x18,
	0xb0, 0x06, 0xd9, 0x5c, 0xe6, 0x48, 0x23, 0xab, 0xbc, 0x73, 0xa7, 0x5d, 0xb1, 0x0a, 0x69, 0xfc,
	0xa1, 0x19, 0x4e, 0x5e, 0x02, 0xd8, 0xfd, 0x92, 0x91, 0xaa, 0xa5, 0x50, 0xd6, 0xdf, 0xcc, 0x46,
	0xbf, 0xab, 0x03, 0x73, 0x03, 0x57, 0xf3, 0x02, 0xb3, 0xc7, 0x2e, 0x21, 0x8f, 0x9f, 0xb3, 0xeb,
	0xfd, 0x96, 0x5d, 0xb8, 0x91, 0xdd, 0x01, 0x84, 0x39, 0xd3, 0x8c, 0x46, 0x93, 0xde, 0x74, 0xeb,
	0x90, 0xcc, 0xbe, 0x25, 0x96, 0x5a, 0x3d, 0x39, 0x86, 0x51, 0x27, 0x5d, 0x63, 0x53, 0x71, 0xa5,
	0xb8, 0x14, 0x7f, 0x7d, 0xcb, 0xe4, 0x04, 0xc6, 0x3f, 0x75, 0xf9, 0xeb, 0x46, 0x30, 0xe0, 0x6a,
	0xc1, 0xca, 0x52, 0xae, 0x6c, 0xdf, 0xc0, 0x1c, 0x72, 0x6a, 0xf0, 0xac, 0x7f, 0x17, 0xd9, 0xdf,
	0x67, 0x19, 0xdb, 0xc7, 0xd1, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x6b, 0x0f, 0xd8, 0x57,
	0x02, 0x00, 0x00,
}
